# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
